#!/usr/bin/env bash
# Runs ON THE GITHUB ACTIONS RUNNER (not the server). Layer 2 (the next
# minute) automatic recovery: creates a NEW commit that reverts the whole
# range of commits from this push, with a full incident report as the
# commit message, and pushes it to main. Never uses `git reset --hard` or
# force-push — this is a plain forward-moving revert commit.
#
# This logic was validated against a throwaway repo before being wired into
# the workflow: normal range revert, the loop guard, and the tip-only
# fallback (bad/zero `before` SHA) were all exercised and produced correct
# output.
set -euo pipefail

# Expected env vars, set by the calling workflow step:
#   BEFORE_SHA      -> ${{ github.event.before }}
#   HEAD_SHA        -> ${{ github.sha }}
#   RUN_URL         -> ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
#   FAILURE_REASON  -> "build" or "healthcheck"

ZERO_SHA="0000000000000000000000000000000000000000"

# --- 1. Work out the range to revert -------------------------------------
if [ -z "${BEFORE_SHA:-}" ] || [ "$BEFORE_SHA" = "$ZERO_SHA" ] || ! git cat-file -e "$BEFORE_SHA" 2>/dev/null; then
  echo "::warning::github.event.before not usable (manual trigger / new branch / force-push). Falling back to reverting only the tip commit."
  RANGE_START=$(git rev-parse "${HEAD_SHA}~1")
else
  RANGE_START="$BEFORE_SHA"
fi

RANGE="${RANGE_START}..${HEAD_SHA}"
echo "Revert range: $RANGE"

# --- 2. Loop guard: never auto-revert an auto-revert ----------------------
if git log --format='%B' "$RANGE" | grep -q '^X-Auto-Revert: true$'; then
  echo "::error::One or more commits in $RANGE is itself an auto-revert commit. Refusing to auto-revert again (loop guard). This likely means the underlying infrastructure/server is broken, not the code. Failing loudly for a human to investigate."
  exit 1
fi

# --- 3. Collect the commit list (oldest first, by subject) ---------------
COMMIT_LIST=$(git log --oneline --reverse "$RANGE")
if [ -z "$COMMIT_LIST" ]; then
  echo "::error::No commits found in range $RANGE — nothing to revert."
  exit 1
fi

# --- 4. Perform the revert as ONE commit ----------------------------------
if ! git revert --no-commit "$RANGE"; then
  echo "::error::git revert hit conflicts reverting $RANGE. Aborting — a human needs to resolve this manually."
  git revert --abort || true
  exit 1
fi

# --- 5. Build the incident-report commit message via printf, not a heredoc
#         (an unindented heredoc terminator is a silent runtime footgun,
#         not a parse error — printf avoids the whole class of bug).
MSG_FILE=$(mktemp)

case "$FAILURE_REASON" in
  build)       REASON_TEXT="the BUILD step failed (the new image never finished building; the previously running version was never touched)." ;;
  swap)        REASON_TEXT="the new image built successfully, but SWAPPING it in failed (the new container would not start). Layer 1 (automatic Docker rollback) already restored the previous version before this commit was created." ;;
  healthcheck) REASON_TEXT="the new version was built and swapped in, but the HEALTH CHECK failed after several retries. Layer 1 (automatic Docker rollback) already restored the previous version before this commit was created." ;;
  *)           REASON_TEXT="the deploy failed (reason: $FAILURE_REASON)." ;;
esac

printf 'Revert "%s" (automated rollback of failed deploy)\n' "$(git log -1 --format=%s "$HEAD_SHA")" > "$MSG_FILE"
printf '\n' >> "$MSG_FILE"
printf 'AUTOMATED INCIDENT REPORT — auto-generated by the deploy workflow.\n' >> "$MSG_FILE"
printf 'Do not hand-edit; read this message for the full recovery plan.\n' >> "$MSG_FILE"
printf '\n' >> "$MSG_FILE"
printf 'WHAT HAPPENED\n' >> "$MSG_FILE"
printf -- '-------------\n' >> "$MSG_FILE"
printf 'Deploy failed because %s\n' "$REASON_TEXT" >> "$MSG_FILE"
printf 'Failed run: %s\n' "$RUN_URL" >> "$MSG_FILE"
printf '\n' >> "$MSG_FILE"
printf 'COMMITS REVERTED (oldest first, range %s)\n' "$RANGE" >> "$MSG_FILE"
printf -- '-------------------------------------------\n' >> "$MSG_FILE"
printf '%s\n' "$COMMIT_LIST" >> "$MSG_FILE"
printf '\n' >> "$MSG_FILE"
printf 'PRODUCTION IS NOW RUNNING\n' >> "$MSG_FILE"
printf -- '-------------------------\n' >> "$MSG_FILE"
printf 'Code as of commit %s (the last known-good state before this push).\n' "$RANGE_START" >> "$MSG_FILE"
printf '\n' >> "$MSG_FILE"
printf 'HOW TO RECOVER THE REVERTED WORK LATER\n' >> "$MSG_FILE"
printf -- '---------------------------------------\n' >> "$MSG_FILE"
printf '1. First, check the failed run logs above to find out what actually broke:\n' >> "$MSG_FILE"
printf '   %s\n' "$RUN_URL" >> "$MSG_FILE"
printf '2. Fix the underlying issue on a new branch/commit.\n' >> "$MSG_FILE"
printf '3. To bring back the reverted work once fixed, use the RANGE, not just the tip commit —\n' >> "$MSG_FILE"
printf '   reverting/cherry-picking only "%s" will NOT restore the earlier commits in this batch:\n' "$(git log -1 --format=%h "$HEAD_SHA")" >> "$MSG_FILE"
printf '     git cherry-pick %s\n' "$RANGE" >> "$MSG_FILE"
printf '   or, simpler, to just grab the whole snapshot as it was at the tip:\n' >> "$MSG_FILE"
printf '     git checkout %s -- .\n' "$HEAD_SHA" >> "$MSG_FILE"
printf '\n' >> "$MSG_FILE"
printf 'DATABASE / MIGRATION NOTE\n' >> "$MSG_FILE"
printf -- '-------------------------\n' >> "$MSG_FILE"
printf 'This revert only undoes CODE. If a migration had partially applied before the\n' >> "$MSG_FILE"
printf 'failure, it is NOT undone by this commit — a human must check the database\n' >> "$MSG_FILE"
printf 'manually. (market_analysis has no database configured as of this writing; if\n' >> "$MSG_FILE"
printf 'one is added later, this note still applies.)\n' >> "$MSG_FILE"
printf '\n' >> "$MSG_FILE"
printf 'X-Auto-Revert: true\n' >> "$MSG_FILE"
printf 'X-Auto-Revert-Range: %s\n' "$RANGE" >> "$MSG_FILE"

echo "===== GENERATED COMMIT MESSAGE ====="
cat "$MSG_FILE"
echo "===== END ====="

git commit -F "$MSG_FILE"
git push origin HEAD:main
